FROM node:20-alpine AS base

WORKDIR /app

ENV PATH ./node_modules/.bin/:$PATH

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn; \
  elif [ -f package-lock.json ]; then npm install; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  else npm i; \
  fi

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]